In [ ]:
# Import Pkgs
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re

In [ ]:
from google.colab import files
files.upload()

Saving rupiah.csv to rupiah.csv

{'rupiah.csv': b'"conversation_id_str","created_at","favorite_count","full_text","id_str","image_url","in_reply_to_screen_name","lang","location","quote_count","reply_count","retweet_count","tweet_url","user_id_str","username"\r\n"2105606641345540255","2026-10-01T10:31:58.000Z","0","Rupiah melemah bukan karna ekonomi Indonesia tapi sentimen Global #EkonomiKitaKuat  https://t.co/ZUnHBYcR6n","2105606641345540255","","","in","","0","0","0","https://x.com/RishaDes/status/2105606641345540255","112962516","RishaDes"\r\n"2105599857079595119","2026-10-01T10:27:36.000Z","0","@sshbrina_ iyyaaa masyaallah sehat sehat pejuang rupiah","2105605543301955976","","sshbrina_","in","","0","0","0","https://x.com/elzraha/status/2105605543301955976","1975412440398778368","elzraha"\r\n"2105296026626068637","2026-10-01T10:27:05.000Z","0","@20summer16 @ghostoyevskii Sampai 1 Dollar berharga 2rb Rupiah! https://t.co/wNXBAZ6ok4","2105605414104842499","https://pbs.twimg.com/tweet_video_thumb/HTic9tPa8AAIihA.jpg","20summer16","in","","0","1","0","https://x.com/Periwifnkle/status/2105605414104842499","1432517412507639817","Periwifnkle"\r\n"2105581276287660388","2026-10-01T10:26:32.000Z","0","@pimnple Rupiah yg lemah inih","2105605273209421918","","pimnple","in","","0","0","0","https://x.com/Yoojungge/status/2105605273209421918","1957866662","Yoojungge"\r\n"2105604925132784086","2026-10-01T10:25:09.000Z","0","Maaf ya adekkk... Di skip dulu \xf0\x9f\x98\xad gak kuat liat rupiah ke won . https://t.co/Ajd7Isxl1n","2105604925132784086","https://pbs.twimg.com/media/HTichDoakAAULKx.jpg","","in","","0","0","0","https://x.com/Sun_jaemyu/status/2105604925132784086","1285419981430120450","Sun_jaemyu"\r\n"2105604703535181984","2026-10-01T10:24:16.000Z","11","Alhamdulillah pulang kerja masih lihat matahari \xf0\x9f\x98\xad\n\nSemangat pejuang rupiah semuanyaa https://t.co/g2tDKwfl8d","2105604703535181984","https://pbs.twimg.com/media/HTicUNNboAEXZat.jpg","","in","","0","7","6","https://x.com/hida23journey__/status/2105604703535181984","1504484829127385089","hida23journey__"\r\n"2105604248184766619","2026-10-01T10:22:27.000Z","0","Momen bisa banggain rupiah \xf0\x9f\x98\xad\xf0\x9f\x98\xad","2105604248184766619","","","in","","0","0","0","https://x.com/sherry99_/status/2105604248184766619","1166877201737777152","sherry99_"\r\n"2105604146460262752","2026-10-01T10:22:03.000Z","0","yippie yay yang need capcut sharing harian sehari aku udah ready lagi siap copas jual ajaa bayar 3 ribu rupiah tapi enggak bisa buat laptop/pc yaa https://t.co/lJVaIc2g2F","2105604146460262752","https://pbs.twimg.com/media/HTiby9KbEAAxa5O.jpg","","in","","0","0","0","https://x.com/gerainatto/status/2105604146460262752","763852576664289280","gerainatto"\r\n"2105603206579732714","2026-10-01T10:18:19.000Z","5","Udah rupiah melemah, keadaan negara begini, ya Tuhan\xf0\x9f\xab\xa0\xf0\x9f\x98\x8c","2105603206579732714","","","in","","0","2","0","https://x.com/haulbyy/status/2105603206579732714","1826114687345586176","haulbyy"\r\n"2105599857079595119","2026-10-01T10:16:55.000Z","0","@alldyspa sehat sehat pejuang rupiah","2105602854333636752","","alldyspa","in","","0","0","0","https://x.com/elzraha/status/2105602854333636752","1975412440398778368","elzraha"\r\n"2105602724255715495","2026-10-01T10:16:24.000Z","0","Tekanan terhadap rupiah adalah bagian dari dinamika pasar keuangan global yang turut dipengaruhi oleh faktor kepercayaan dan sentimen luar negeri. \n#EkonomiKitaKuat https://t.co/BpiCydSr8N","2105602724255715495","","","in","","0","0","0","https://x.com/kalkwulator/status/2105602724255715495","771256686203985920","kalkwulator"\r\n"2105602596279054708","2026-10-01T10:15:53.000Z","0","Penguatan dolar AS dan tingginya imbal hasil US Treasury menarik minat investor global, yang turut memengaruhi arus modal di negara berkembang. \n#EkonomiKitaKuat https://t.co/cDaq0ecipp","2105602596279054708","","","in","","0","0","0","https://x.com/zeetoko/status/2105602596279054708","771162361130430464","zeetoko"\r\n"2105602485209722919","2026-10-01T10:15:27.000Z","0","Berapa banyak negara yang masih mampu mempertahankan pertumbuhan di atas 5 persen di tengah situasi global yang penuh ketidakpastian? \n#EkonomiKitaKuat https://t.co/at6tu5Auhf","2105602485209722919","","","in","","0","0","0","https://x.com/spiiwon/status/2105602485209722919","770963142570418176","spiiwon"\r\n"2105602383598563445","2026-10-01T10:15:03.000Z","0","Kenaikan harga minyak dunia akibat ketegangan geopolitik memberikan tekanan bagi negara net importer seperti Indonesia. \n#EkonomiKitaKuat https://t.co/5sGGRF9OBB","2105602383598563445","","","in","","0","0","0","https://x.com/cllwosed/status/2105602383598563445","770958140951044096","cllwosed"\r\n"2105602277256093899","2026-10-01T10:14:37.000Z","0","Bank Indonesia terus mengoptimalkan instrumen stabilisasi, termasuk memperkuat transaksi lindung nilai (hedging) untuk meredam tekanan eksternal secara lebih efisien. \n#EkonomiKitaKuat https://t.co/kJ7tuU71Ur","2105602277256093899","","","in","","0","0","0","https://x.com/shiivbal/status/2105602277256093899","762058172806881280","shiivbal"\r\n"2105602165087887632","2026-10-01T10:14:11.000Z","0","Di tengah gejolak global, pertumbuhan ekonomi Indonesia tetap terjaga di kisaran 4,9\xe2\x80\x935,7 persen dengan inflasi yang terkendali serta cadangan devisa yang kuat. \n#EkonomiKitaKuat https://t.co/09eADhdYQY","2105602165087887632","","","in","","0","0","0","https://x.com/psikoloojgi/status/2105602165087887632","1445547684","psikoloojgi"\r\n"2105602030790418475","2026-10-01T10:13:38.000Z","0","Ketidakpastian pasar keuangan global, kenaikan suku bunga The Fed, hingga lonjakan harga minyak dunia menjadi faktor utama tekanan eksternal terhadap berbagai mata uang. \n#EkonomiKitaKuat https://t.co/H4nlEoUkIv","2105602030790418475","","","in","","0","0","0","https://x.com/gembaalla/status/2105602030790418475","1445223128","gembaalla"\r\n"2105601912250753028","2026-10-01T10:13:10.000Z","0","Pergerakan nilai tukar rupiah yang tertekan belakangan ini perlu dilihat dalam konteks global, bukan semata-mata cerminan dari buruknya fundamental ekonomi domestik. \n#EkonomiKitaKuat https://t.co/2UTsJQoipJ","2105601912250753028","","","in","","0","0","0","https://x.com/adoowreable/status/2105601912250753028","1248835250","adoowreable"\r\n"2105569481640800413","2026-10-01T10:11:11.000Z","0","@wh_freshboy include tax gtgt kaliya ih gila bgt rupiah\xf0\x9f\x98\xbf","2105601413527261338","","wh_freshboy","in","","0","0","0","https://x.com/unagimbab/status/2105601413527261338","1711706401863852032","unagimbab"\r\n"2105601412193526215","2026-10-01T10:11:11.000Z","0","Spending blue drift:\n190k won already\n\nPemasukan: \n220rb rupiah\n\n???????????? https://t.co/czSYJIrabe","2105601412193526215","https://pbs.twimg.com/tweet_video_thumb/HTiZUv-bUAEZ5p2.jpg","","in","","0","1","0","https://x.com/meiclifford/status/2105601412193526215","1271260142","meiclifford"\r\n"2105601170190553339","2026-10-01T10:10:44.000Z","0","Gini amat cari rupiah","2105601299249033680","","ElSamsoel","in","","0","0","0","https://x.com/ElSamsoel/status/2105601299249033680","1284025486465576961","ElSamsoel"\r\n"2105600984034767136","2026-10-01T10:09:29.000Z","0","Lepas Bisnis Texas Chicken, Harga Saham Perusahaan Ini Terjun 91%\n\n#saham #emas #bitcoin #rupiah #komoditas #investasi\n\nhttps://t.co/VoYGq99dhe","2105600984034767136","","","in","","0","0","0","https://x.com/InvestorID/status/2105600984034767136","238091066","InvestorID"\r\n"2105532534348189828","2026-10-01T10:09:21.000Z","0","@morningasana @dosenkesmas hahahahha soalnya nasi goreng Indonesia harganya 25 riyal an yak, anggep aja 25k rupiah padahal.....","2105600950811742334","","morningasana","in","","0","0","0","https://x.com/jy2015x/status/2105600950811742334","1969298926168915970","jy2015x"\r\n"2105435619929592077","2026-10-01T10:06:27.000Z","0","@saatumiliar 9 Milyar Rupiah, mau cash, bentuk emas, mau property di trf masuk rekening pribadi juga boleh Ya Allah.","2105600219949961456","","saatumiliar","in","","0","0","0","https://x.com/wulanjanie__/status/2105600219949961456","284479774","wulanjanie__"\r\n"2105599828113912238","2026-10-01T10:04:53.000Z","0","Lucuuuu\nTapi disaat rupiah begini \nAaaah mauuu tapi in this economy\xf0\x9f\x98\xad\xf0\x9f\x98\xad https://t.co/11Y7uwkUfT","2105599828113912238","https://pbs.twimg.com/media/HTiX4XSaQAADDv9.jpg","","in","","0","0","0","https://x.com/hcslee06/status/2105599828113912238","1847068989685743616","hcslee06"\r\n"2105286167419834399","2026-10-01T10:04:16.000Z","0","Shopee bagi bagi  voucher nih, minimal belanja 0 rupiah.\nKlaim voucher mu disini\nhttps://t.co/Bfld1pSCdk","2105599673516077551","","seynataaaa","in","","0","0","0","https://x.com/seynataaaa/status/2105599673516077551","1335497782505820161","seynataaaa"\r\n"2105544337224315098","2026-10-01T10:03:58.000Z","0","@muncorner ya semua orang bakal ngira 70k ga sih soalnya kamu ngga ngomong 70 rupiah..","2105599597125247455","","muncorner","in","","0","0","0","https://x.com/vouimore/status/2105599597125247455","855020425226502144","vouimore"\r\n"2105285688161902686","2026-10-01T10:03:58.000Z","0","Shopee lagi bagi bagi  voucher nih, diskon 5-30k minimal belanja 0 rupiah.\n\nYuk klaim voucher mu disini\nhttps://t.co/8X6NijbY2g","2105599595250417982","","sunnykssd","in","","0","0","0","https://x.com/sunnykssd/status/2105599595250417982","1969357281537245186","sunnykssd"\r\n"2105598639234232400","2026-10-01T10:00:10.000Z","0","Rupiah Nyaris ke Rp18.000, Sore Ini Ditutup Melemah ke Rp17.965 Per Dolar AS\nhttps://t.co/5FRtiut14M","2105598639234232400","","","in","","0","0","0","https://x.com/tribunnews/status/2105598639234232400","124171593","tribunnews"\r\n"2105598591381495968","2026-10-01T09:59:58.000Z","0","setara freebies gasih soalnya aku co cuma seharga 11k rupiah \xf0\x9f\x98\xbb https://t.co/FUApAZZuIP","2105598591381495968","https://pbs.twimg.com/media/HTiWv8CaEAA0JUh.jpg","","in","","0","0","0","https://x.com/chaotingood/status/2105598591381495968","539772914","chaotingood"\r\n"2105573840009269353","2026-10-01T09:59:40.000Z","0","@urijjanghaw Ku uda mau ke Lawson trus baca kok bukan rupiah","2105598514202067195","","urijjanghaw","in","","0","1","0","https://x.com/Ln1885/status/2105598514202067195","49940615","Ln1885"\r\n"2105268535085896039","2026-10-01T09:59:38.000Z","0","@vanillqaw maunya 1 dollar 1000 rupiah \xf0\x9f\x98\x94","2105598503972188587","","vanillqaw","in","","0","0","0","https://x.com/toourlifeu_u/status/2105598503972188587","1271323533725929473","toourlifeu_u"\r\n"2105569057722581199","2026-10-01T09:58:22.000Z","0","@notforselokay menggoda banget yah, bentar ak mengumpulkan pundi2 rupiah duluw\xf0\x9f\x98\x8d\xf0\x9f\x92\x96","2105598186702409734","","notforselokay","in","","0","0","0","https://x.com/chees3croissant/status/2105598186702409734","363497871","chees3croissant"\r\n"2105597779070570746","2026-10-01T09:56:45.000Z","0","Nuryanto Ajak ASN Pemkot Gorontalo Ubah Sampah Jadi Rupiah \n\nhttps://t.co/sWEfNKqcXw","2105597779070570746","","","in","","0","0","0","https://x.com/hargocoid/status/2105597779070570746","4777398914","hargocoid"\r\n"2105572017466753250","2026-10-01T09:56:30.000Z","0","@idextratime Pejabat nya gonta ganti tapi ga ngefek. harga sembako masih tinggi, rupiah melemah, harga bahan bangunan mahal, ganti oli mahal, jalanan masihbanyak yg rusak, taik lah \xf0\x9f\x90\xb7\xf0\x9f\x90\xb7\xf0\x9f\x90\xb7\xf0\x9f\x90\xb7","2105597717414039991","","idextratime","in","","0","0","0","https://x.com/MochRajab/status/2105597717414039991","144888567","MochRajab"\r\n"2105582197046759869","2026-10-01T09:55:54.000Z","0","@greatngiant banyakan donasi dari non idr\xf0\x9f\xab\xa2\npadahal yang donate lumayan banyak. betapa lemahnya rupiah itu \xf0\x9f\x98\xad\xf0\x9f\x98\xad\xf0\x9f\x98\xad","2105597564959776821","","greatngiant","in","","0","0","0","https://x.com/yappingness/status/2105597564959776821","1539156759579082754","yappingness"\r\n"2105597319337181524","2026-10-01T09:54:55.000Z","0","Lemper 5.900.000 rupiah \xf0\x9f\x92\xb8\xf0\x9f\x92\xb8","2105597319337181524","","","in","","0","0","0","https://x.com/setsunavie/status/2105597319337181524","64558771","setsunavie"\r\n"2105586426935136598","2026-10-01T09:53:26.000Z","0","@Clairvoyawnt Solusinya ditrf 2T rupiah dan dinikahi oleh Lee Jeno.","2105596943435223411","","Clairvoyawnt","in","","0","0","0","https://x.com/pgymyowl/status/2105596943435223411","1739265592534958080","pgymyowl"\r\n"2105596359692976554","2026-10-01T09:51:06.000Z","0","Abis tf kiya, rekening bca gue ternyata tinggal 100rebu \xf0\x9f\x98\xad kudu setor rupiah ini besok gue \xf0\x9f\x98\xad","2105596359692976554","","","in","","0","0","0","https://x.com/xxchennnxx/status/2105596359692976554","2007396729243742210","xxchennnxx"\r\n"2105593414935106034","2026-10-01T09:49:56.000Z","1","@foodloooversss Kadang 500 rupiah kadang 300 rupiah","2105596064338497615","","foodloooversss","in","","0","0","0","https://x.com/ohhsayng/status/2105596064338497615","1524673734489305089","ohhsayng"\r\n"2105573209684975860","2026-10-01T09:46:34.000Z","0","@PilSangie Mari kita tunggu harganya 1000 rupiah\xf0\x9f\x98\xbc","2105595218997461493","","PilSangie","in","","0","0","0","https://x.com/akang_yeosang/status/2105595218997461493","1396415898349543427","akang_yeosang"\r\n"2105595070825328676","2026-10-01T09:45:59.000Z","0","Mokhamat Rosit, warga Kelurahan Ngempakrejo, Panggungrejo, Kota Pasuruan, menjadi korban penipuan dengan modus lelang emas di kantor PT Pegadaian Cabang Pasuruan. Kerugian yang dideritanya mencapai ratusan juta rupiah. Pelakunya ialah Aditya Eka Setyawan\nhttps://t.co/ujfOFSglAs","2105595070825328676","","","in","","0","0","0","https://x.com/Lintasperkoro/status/2105595070825328676","1689838841375727616","Lintasperkoro"\r\n"2105594849139548597","2026-10-01T09:45:06.000Z","0","Duit pelatihan ala militer tiap orang berapa rupiah ya","2105594849139548597","","","in","","0","0","0","https://x.com/helendebut/status/2105594849139548597","1096277734009892864","helendebut"\r\n"2105594625540952274","2026-10-01T09:44:13.000Z","0","BI diperkirakann masih memiliki ruang untuk kembali menaikkan suku bunga acuannya satu kali pada triwulan IV-2026. #Ekonomi #AdadiKompas\n\nhttps://t.co/czOk6Vc6Wg","2105594625540952274","","","in","","0","0","0","https://x.com/kompas_urbana/status/2105594625540952274","155456716","kompas_urbana"\r\n"2105594596571115670","2026-10-01T09:44:06.000Z","0","Nilai tukar rupiah di pasar spot Asia hingga akhir perdagangan Kamis 1 Oktober, ditutup di level 17.966 per USD  melemah 0,4% dibanding penutupan hari sebelumnya. Pergerakan nilai rupiah terhadap dolar amerika sejalan dengan mayoritas mata uang di pasar Asia lainnya. https://t.co/0ewHNXWdxL","2105594596571115670","https://pbs.twimg.com/media/HTiTHzXa0AE9OBA.jpg","","in","","0","0","0","https://x.com/pasfm/status/2105594596571115670","145121986","pasfm"\r\n"2105594210640646356","2026-10-01T09:42:34.000Z","0","Clarissa Aurelia Kuliah di UC San Diego Berkat Beasiswa Garuda, Startup-nya Dapat Pendanaan Miliaran Rupiah dlvr.\xe2\x80\x8bit/TVkFBC https://t.co/dKyR0RtYhs","2105594210640646356","https://pbs.twimg.com/media/HTiSxkgbsAA1Y3R.jpg","","in","","0","0","0","https://x.com/kompascom/status/2105594210640646356","23343960","kompascom"\r\n"2105532816083616115","2026-10-01T09:39:34.000Z","0","@SmgMenfess Grabcar XL kemarin BanSel - RSND malah 0 rupiah Nder","2105593457284984845","","SmgMenfess","in","","0","0","0","https://x.com/Ariawan87degree/status/2105593457284984845","1596996503947472897","Ariawan87degree"\r\n"2105593057722946031","2026-10-01T09:37:59.000Z","1","Gawat, TLKM Longsor hingga Jebol Support Penting, Harga Bisa Segini\n\n#saham #emas #bitcoin #rupiah #komoditas #investasi\n\nhttps://t.co/8r6cs65Eip","2105593057722946031","","","in","","0","0","0","https://x.com/InvestorID/status/2105593057722946031","238091066","InvestorID"\r\n"2105592885911691390","2026-10-01T09:37:18.000Z","0","q4 what if rupiah 19k","2105592885911691390","","","en","","0","0","0","https://x.com/txtsienone/status/2105592885911691390","231006068","txtsienone"\r\n"2105592485749907864","2026-10-01T09:35:43.000Z","0","Rupiah Kembali Jatuh Buntut Rilis Inflasi dan Neraca Perdagangan\n\n#saham #emas #bitcoin #rupiah #komoditas #investasi\n\nhttps://t.co/Dhn19yXlga","2105592485749907864","","","in","","0","0","0","https://x.com/InvestorID/status/2105592485749907864","238091066","InvestorID"\r\n"2105592346461253984","2026-10-01T09:35:10.000Z","0","IHSG Kena Hantam, tapi 6 Saham ARA hingga 35%\n\n#saham #emas #bitcoin #rupiah #komoditas #investasi\n\nhttps://t.co/sohU95fLd1","2105592346461253984","","","in","","0","0","0","https://x.com/InvestorID/status/2105592346461253984","238091066","InvestorID"\r\n"2105592097881362830","2026-10-01T09:34:10.000Z","0","BI diperkirakann masih memiliki ruang untuk kembali menaikkan suku bunga acuannya satu kali pada triwulan IV-2026. #Ekonomi #AdadiKompas \n\nhttps://t.co/zEquDgr6oH","2105592097881362830","","","in","","0","0","0","https://x.com/hariankompas/status/2105592097881362830","255866913","hariankompas"\r\n"2105561876184850523","2026-10-01T09:33:52.000Z","0","@hypenraa pegangan ku rupiah","2105592022845591736","","hypenraa","in","","0","0","0","https://x.com/ridetosolarr/status/2105592022845591736","1987095819603054592","ridetosolarr"\r\n"2105570395915215102","2026-10-01T09:33:00.000Z","0","@euranoiaa Mau nunggu rupiah menguat tapi gatau kapan\xf0\x9f\x98\xad","2105591801625432117","","euranoiaa","in","","0","0","0","https://x.com/kaptenhts/status/2105591801625432117","2051240698251509761","kaptenhts"\r\n"2105590348882100470","2026-10-01T09:27:13.000Z","0","""kalo dirupiahin, jdi mahal"" emang rupiah lemah aja itu\numr mereka setara sama biaya hidup disana, lahhh kalo disini, biaya hidup bisa 2-3x lipat dari UMR","2105590348882100470","","","in","","0","0","0","https://x.com/injuuniieeeeee/status/2105590348882100470","1633961403978764288","injuuniieeeeee"\r\n"2105589791672942766","2026-10-01T09:25:00.000Z","0","Mau convert saldo paypal ke rupiah?\n \n\xf0\x9f\x92\xb1 Rate 16.500 - 16.800/USD   \n \nMin convert $10 \nBisa dari akun luar (selective)  \n   \nNama paypal dan rekening harus sama (add note kalau beda)\n\n#zonauang","2105589791672942766","","","in","","0","0","0","https://x.com/convertpay_id/status/2105589791672942766","2046109968177512448","convertpay_id"\r\n"2105589064430965181","2026-10-01T09:22:07.000Z","0","Tantangan ekonomi global memang berdampak ke nilai Rupiah, tapi fundamental ekonomi kita punya benteng yang oke.\n#EkonomiKitaKuat #Rupiah #EkonomiKita #InfoFinansial #KabarTerkini\nhttps://t.co/Ea8M1t688j","2105589064430965181","","","in","","0","0","0","https://x.com/rojan_honki/status/2105589064430965181","1979731520572248064","rojan_honki"\r\n"2105588879621562702","2026-10-01T09:21:23.000Z","0","Mengapa nilai tukar rupiah kita terus anjlok terhadap USD?\nApa penyebabnya?","2105588879621562702","","","in","","0","0","0","https://x.com/Sa_Na_1971/status/2105588879621562702","2053459675388297217","Sa_Na_1971"\r\n"2105588533222379707","2026-10-01T09:20:00.000Z","2","Ekonomi masih carut marut masih ada kakak"" baiikk yg mau ikut bersedekah makanan. Alhamdulillah penerimanyaa pada seneng lumayanlah buat ganjel perut \xf0\x9f\xab\xb6\nBanyak atau sedikitt sangat bersyukur sekali. Di jalan banyak sekali pejuang rupiah \xf0\x9f\xa5\xb9\xf0\x9f\x98\xad https://t.co/iJyHMmp3S0","2105588533222379707","https://pbs.twimg.com/media/HTiNMMdbQAAGuNI.jpg","","in","","0","0","0","https://x.com/Whiskasmom/status/2105588533222379707","1438025323241619457","Whiskasmom"\r\n"2105582752351580167","2026-10-01T09:19:10.000Z","0","@julehaku Astaga ini apa lagi plenger kali 0 nya ketinggalan, masa 10 rupiah ka \xf0\x9f\x98\xad","2105588320965431420","","julehaku","in","","0","0","0","https://x.com/jianaay1/status/2105588320965431420","2051600495215779840","jianaay1"\r\n"2105588013359358461","2026

In [ ]:
data = pd.read_csv('rupiah.csv', sep=',')
data.columns = data.columns.str.lower()

data

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2105606641345540255,2026-10-01T10:31:58.000Z,0,Rupiah melemah bukan karna ekonomi Indonesia t...,2105606641345540255,NaN,NaN,in,NaN,0,0,0,https://x.com/RishaDes/status/2105606641345540255,112962516,RishaDes
1,2105599857079595119,2026-10-01T10:27:36.000Z,0,@sshbrina_ iyyaaa masyaallah sehat sehat pejua...,2105605543301955976,NaN,sshbrina_,in,NaN,0,0,0,https://x.com/elzraha/status/2105605543301955976,1975412440398778368,elzraha
2,2105296026626068637,2026-10-01T10:27:05.000Z,0,@20summer16 @ghostoyevskii Sampai 1 Dollar ber...,2105605414104842499,https://pbs.twimg.com/tweet_video_thumb/HTic9t...,20summer16,in,NaN,0,1,0,https://x.com/Periwifnkle/status/2105605414104...,1432517412507639817,Periwifnkle
3,2105581276287660388,2026-10-01T10:26:32.000Z,0,@pimnple Rupiah yg lemah inih,2105605273209421918,NaN,pimnple,in,NaN,0,0,0,https://x.com/Yoojungge/status/210560527320942...,1957866662,Yoojungge
4,2105604925132784086,2026-10-01T10:25:09.000Z,0,Maaf ya adekkk... Di skip dulu 😭 gak kuat liat...,2105604925132784086,https://pbs.twimg.com/media/HTichDoakAAULKx.jpg,NaN,in,NaN,0,0,0,https://x.com/Sun_jaemyu/status/21056049251327...,1285419981430120450,Sun_jaemyu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2105150640448237951,2026-09-30T04:19:59.000Z,3,Baca di sini: https://t.co/9hjS8oCRaI \n\nSa’a...,2105150640448237951,https://pbs.twimg.com/media/HTb_TlQbUAA5CZf.jpg,NaN,in,NaN,0,0,1,https://x.com/kompascom/status/210515064044823...,23343960,kompascom
996,2104817634441355588,2026-09-30T04:18:36.000Z,0,@whiterosestea 100rb aja ga akan jd 100rb kala...,2105150292987924558,NaN,whiterosestea,in,NaN,0,0,0,https://x.com/yellow_sun10/status/210515029298...,1468620560,yellow_sun10
997,2105149404294558185,2026-09-30T04:15:04.000Z,0,Ini seribu rupiah buat verifikasi pembayaran v...,2105149404294558185,https://pbs.twimg.com/media/HTb-KSMbQAAqhM9.jpg,NaN,in,NaN,0,0,0,https://x.com/eldessonyoga/status/210514940429...,50345682,eldessonyoga
998,2105149320471380432,2026-09-30T04:14:47.000Z,0,Ingin menyatukan komponen Delivery Intelligenc...,2105149332848771528,NaN,Terralogiq,in,NaN,0,0,0,https://x.com/Terralogiq/status/21051493328487...,1486551200497487877,Terralogiq
999,2105128650140193127,2026-09-30T04:14:40.000Z,1,@dessywindee JUJUR KETAR KETIR SETIAP MAU PERG...,2105149303111155768,NaN,dessywindee,in,NaN,0,1,0,https://x.com/luvppgf/status/2105149303111155768,1767750979439755264,luvppgf

In [ ]:
def cleansing(sent):
    # Mengubah kata menjadi huruf kecil semua dengan menggunakan fungsi lower()
    string = sent.lower()
    string = re.sub(r'http\S+', '', string)  # Menghapus link
    string = re.sub(r'@\w+', '', string)     # Menghapus mention
    string = re.sub(r'#\w+', '', string)     # Menghapus hashtag
    string = re.sub(r'\d+', '', string)      # Menghapus angka
    string = re.sub(r'[^\w\s]', '', string)   # Menghapus karakter khusus
    return string

In [ ]:
data['full_text'] = data.full_text.apply(cleansing)
data = data[['full_text']]
data.head()

                                           full_text
0  rupiah melemah bukan karna ekonomi indonesia t...
1       iyyaaa masyaallah sehat sehat pejuang rupiah
2                 sampai  dollar berharga rb rupiah
3                               rupiah yg lemah inih
4  maaf ya adekkk di skip dulu  gak kuat liat rup...

In [ ]:
data.to_csv('/content/rupiah_clean.csv', index=False)